### ISSUE TITLE
Environment Details?

### ISSUE THREAD

**Issue by SilentG5** [startmatter/confluence2notion#1]
I'm running some tests of confluence2notion using Debian Stretch and Python3 and I am running up against this when I run the tool:

`Traceback (most recent call last):
  File "confluence2notion.py", line 9, in <module>
    from converter import BlockConverter
  File "/usr/local/src/confluence2notion-master/converter.py", line 29, in <module>
    import confluence
  File "/usr/local/src/confluence2notion-master/confluence.py", line 54
    return self.get_list(f"{self.base_url}/rest/api/space")`

My command looks something like this:

`python3 confluence2notion.py "https://something.atlassian.net/wiki" https://www.notion.so/my parent page url`

I'm wondering if matching the OS and Python environment that you generally use would help me out here or if there is a series of procedural steps I should be using beyond spin up VM, install required Python modules via pip3, export variables, run command.

**Comment by SilentG5** [comment]
I worked out setting the log level to DEBUG and found a couple of lines in confluence.py with the same issue.

Example:

`return self.get_list(f"{self.base_url}/rest/api/space")`

Should be this:

`return self.get_list("{self.base_url}/rest/api/space")`

The extra 'f' appears to be the culprit. 

Found that same thing in 3 or 4 places in confluence.py

**Comment by ddemid** [comment]
Minimum supported python version is 3.6 

https://www.python.org/dev/peps/pep-0498/
